from src.test_generator.schemas import GeneratedTest
from src.test_generator.test_runner import run_generated_test


def test_run_generated_test(tmp_path):
    # Create a tiny repository
    target_file = tmp_path / "target.py"
    target_file.write_text(
        """
def add(a, b):
    return a + b
"""
    )

    # Pretend this test was generated by the LLM
    generated_test = GeneratedTest(
    test_code="""
import sys
sys.path.insert(0, "/repo")

from target import add


def test_add():
    assert add(2, 3) == 5
""",
    description="Verify that add() correctly adds two numbers.",
)

    result = run_generated_test(
        str(tmp_path),
        generated_test,
    )

    assert result.passed is True
    assert result.ran_successfully is True
    assert result.timed_out is False