"""
Directory and file filtering rules for repo ingestion.

Kept separate from repo_loader.py on purpose: Day 2 hardening (binary files,
generated files, huge files, etc.) will extend this file, not the core walk logic.
"""

MAX_FILE_SIZE = 1 * 1024 * 1024
# Directories we never want to walk into, regardless of repo.
IGNORED_DIR_NAMES = {
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    "build",
    "dist",
    "*.egg-info",  # handled via endswith check, not exact match
    "node_modules",
    ".idea",
    ".vscode",
}

generated_markers = [
    "auto-generated",
    "autogenerated",
    "@generated",
    "do not edit",
    "automatically generated",
]


BINARY_SIGNATURES = {
    "PNG": b"\x89PNG\r\n\x1a\n",
    "JPEG": b"\xff\xd8\xff",
    "PDF": b"%PDF",
    "ZIP": b"PK\x03\x04",
    "GIF": b"GIF8",
    "GZIP": b"\x1f\x8b",
    "RAR": b"Rar!\x1a\x07",
    "7-Zip": b"7z\xbc\xaf\x27\x1c",
    "ELF": b"\x7fELF",
}


def is_ignored_dir(dirname: str) -> bool:
    """Return True if this directory should be skipped entirely."""
    if dirname in IGNORED_DIR_NAMES:
        return True
    return bool(dirname.endswith(".egg-info"))


def is_python_file(filename: str) -> bool:
    """Day 1 scope: Python only. Extend this for multi-language support later."""
    return filename.endswith(".py")


def is_generated_file(content: str) -> bool:
    lines = content.splitlines()[:10]
    for line in lines:
        line = line.lower()

        for marker in generated_markers:
            if marker in line:
                return True

    return False


def is_binary_file(file_path: str) -> bool:
    """Returns True if the file appears to be binary."""
    with open(file_path, "rb") as f:
        chunk = f.read(8192)

    if not chunk:
        return False

    if b"\x00" in chunk:
        return True

    char_count = 0
    for byte in chunk:
        if 0 <= byte < 32 and byte not in (9, 10, 13):
            char_count = char_count + 1

    text_like_byte = 0
    for byte in chunk:
        if byte in range(32, 127) or byte in (9, 10, 13):
            text_like_byte = text_like_byte + 1

    printable_ratio = text_like_byte / len(chunk)

    if printable_ratio < 0.3:
        return True

    char_ratio = char_count / len(chunk)
    if char_ratio > 0.3:
        return True

    for file_type, signature in BINARY_SIGNATURES.items():
        if chunk.startswith(signature):
            return True

    return False
